apiVersion: v1
kind: Pod
metadata:
  name: consul-discovery
spec:
  containers:
  - name: consul
    image: consul:1.7.0
    command: ["consul", "agent", "-config-file=/etc/consul/config.json"]
    volumeMounts:
    - name: consul-config
      mountPath: /etc/consul
  volumes:
  - name: consul-config
    configMap:
      name: consul-config