apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ai-models
  labels:
    app: ollama
spec:
  type: LoadBalancer
  selector:
    app: ollama
  ports:
  - port: 80
    targetPort: 11434
    protocol: TCP
    name: api
  sessionAffinity: None