apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: ai-models
spec:
  accessModes:
    - ReadWriteMany  # Multiple pods can access simultaneously
  resources:
    requests:
      storage: 100Gi  # Adjust based on model sizes
  storageClassName: fast-ssd  # Use SSD for better performance
